// flow-typed signature: 9862626deb089ee9be52e5ec7a47f3f3
// flow-typed version: <<STUB>>/catharsis_v0.8.11/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'catharsis'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'catharsis' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'catharsis/bin/parse' {
  declare module.exports: any;
}

declare module 'catharsis/catharsis' {
  declare module.exports: any;
}

declare module 'catharsis/lib/describe' {
  declare module.exports: any;
}

declare module 'catharsis/lib/parser' {
  declare module.exports: any;
}

declare module 'catharsis/lib/schema' {
  declare module.exports: any;
}

declare module 'catharsis/lib/stringify' {
  declare module.exports: any;
}

declare module 'catharsis/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'catharsis/bin/parse.js' {
  declare module.exports: $Exports<'catharsis/bin/parse'>;
}
declare module 'catharsis/catharsis.js' {
  declare module.exports: $Exports<'catharsis/catharsis'>;
}
declare module 'catharsis/lib/describe.js' {
  declare module.exports: $Exports<'catharsis/lib/describe'>;
}
declare module 'catharsis/lib/parser.js' {
  declare module.exports: $Exports<'catharsis/lib/parser'>;
}
declare module 'catharsis/lib/schema.js' {
  declare module.exports: $Exports<'catharsis/lib/schema'>;
}
declare module 'catharsis/lib/stringify.js' {
  declare module.exports: $Exports<'catharsis/lib/stringify'>;
}
declare module 'catharsis/lib/types.js' {
  declare module.exports: $Exports<'catharsis/lib/types'>;
}
