// flow-typed signature: 6c7ca4e5a45485960f997c67f124d204
// flow-typed version: <<STUB>>/@webdoc/default-template_v^1.6.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/default-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/default-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webdoc/default-template/Gulpfile.babel' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/crawl/crawl-reference-explorer' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/crawl/crawl-tutorials' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/crawl/crawl' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/crawl' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/explorer' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/linker' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/renderer-plugins/category-filter' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/renderer-plugins/index-sorter' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/renderer-plugins/preprocess' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/renderer-plugins/signature' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/types' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/helper/workers/hl' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/publish' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerCategoryItem' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerFilter' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerHeader' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerItem' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer/helpers' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Explorer/useExplorerStyles' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Footer/Footer' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Footer' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Header/Header' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Header' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/components/Header/Search' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/resource' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/src/app/store' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/static/scripts/default-template' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/static/scripts/linenumber' {
  declare module.exports: any;
}

declare module '@webdoc/default-template/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webdoc/default-template/Gulpfile.babel.js' {
  declare module.exports: $Exports<'@webdoc/default-template/Gulpfile.babel'>;
}
declare module '@webdoc/default-template/helper/crawl/crawl-reference-explorer.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/crawl/crawl-reference-explorer'>;
}
declare module '@webdoc/default-template/helper/crawl/crawl-tutorials.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/crawl/crawl-tutorials'>;
}
declare module '@webdoc/default-template/helper/crawl/crawl.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/crawl/crawl'>;
}
declare module '@webdoc/default-template/helper/crawl/index' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/crawl'>;
}
declare module '@webdoc/default-template/helper/crawl/index.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/crawl'>;
}
declare module '@webdoc/default-template/helper/explorer.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/explorer'>;
}
declare module '@webdoc/default-template/helper/linker.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/linker'>;
}
declare module '@webdoc/default-template/helper/renderer-plugins/category-filter.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/renderer-plugins/category-filter'>;
}
declare module '@webdoc/default-template/helper/renderer-plugins/index-sorter.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/renderer-plugins/index-sorter'>;
}
declare module '@webdoc/default-template/helper/renderer-plugins/preprocess.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/renderer-plugins/preprocess'>;
}
declare module '@webdoc/default-template/helper/renderer-plugins/signature.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/renderer-plugins/signature'>;
}
declare module '@webdoc/default-template/helper/types.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/types'>;
}
declare module '@webdoc/default-template/helper/workers/hl.js' {
  declare module.exports: $Exports<'@webdoc/default-template/helper/workers/hl'>;
}
declare module '@webdoc/default-template/publish.js' {
  declare module.exports: $Exports<'@webdoc/default-template/publish'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerCategoryItem.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer/ExplorerCategoryItem'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerFilter.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer/ExplorerFilter'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerHeader.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer/ExplorerHeader'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/ExplorerItem.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer/ExplorerItem'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/helpers.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer/helpers'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/index' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/index.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer'>;
}
declare module '@webdoc/default-template/src/app/components/Explorer/useExplorerStyles.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Explorer/useExplorerStyles'>;
}
declare module '@webdoc/default-template/src/app/components/Footer/Footer.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Footer/Footer'>;
}
declare module '@webdoc/default-template/src/app/components/Footer/index' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Footer'>;
}
declare module '@webdoc/default-template/src/app/components/Footer/index.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Footer'>;
}
declare module '@webdoc/default-template/src/app/components/Header/Header.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Header/Header'>;
}
declare module '@webdoc/default-template/src/app/components/Header/index' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Header'>;
}
declare module '@webdoc/default-template/src/app/components/Header/index.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Header'>;
}
declare module '@webdoc/default-template/src/app/components/Header/Search.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/components/Header/Search'>;
}
declare module '@webdoc/default-template/src/app/index' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app'>;
}
declare module '@webdoc/default-template/src/app/index.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app'>;
}
declare module '@webdoc/default-template/src/app/resource.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/resource'>;
}
declare module '@webdoc/default-template/src/app/store.js' {
  declare module.exports: $Exports<'@webdoc/default-template/src/app/store'>;
}
declare module '@webdoc/default-template/static/scripts/default-template.js' {
  declare module.exports: $Exports<'@webdoc/default-template/static/scripts/default-template'>;
}
declare module '@webdoc/default-template/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'@webdoc/default-template/static/scripts/linenumber'>;
}
declare module '@webdoc/default-template/webpack.config.js' {
  declare module.exports: $Exports<'@webdoc/default-template/webpack.config'>;
}
