// flow-typed signature: 3d15a35acb5f3022c35e06fb318c0408
// flow-typed version: <<STUB>>/@webdoc/eslint-config_v^1.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/eslint-config'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/eslint-config' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@webdoc/eslint-config/index' {
  declare module.exports: $Exports<'@webdoc/eslint-config'>;
}
declare module '@webdoc/eslint-config/index.js' {
  declare module.exports: $Exports<'@webdoc/eslint-config'>;
}
