// flow-typed signature: 4fdf974851df4a3002d5c37abd6c9a77
// flow-typed version: <<STUB>>/@webdoc/legacy-template_v^1.6.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/legacy-template'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/legacy-template' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webdoc/legacy-template/__tests__/webdoc-legacy-template.test' {
  declare module.exports: any;
}

declare module '@webdoc/legacy-template/helper' {
  declare module.exports: any;
}

declare module '@webdoc/legacy-template/publish' {
  declare module.exports: any;
}

declare module '@webdoc/legacy-template/src/AttributesBuilder' {
  declare module.exports: any;
}

declare module '@webdoc/legacy-template/src/SignatureBuilder' {
  declare module.exports: any;
}

declare module '@webdoc/legacy-template/static/scripts/linenumber' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webdoc/legacy-template/__tests__/webdoc-legacy-template.test.js' {
  declare module.exports: $Exports<'@webdoc/legacy-template/__tests__/webdoc-legacy-template.test'>;
}
declare module '@webdoc/legacy-template/helper.js' {
  declare module.exports: $Exports<'@webdoc/legacy-template/helper'>;
}
declare module '@webdoc/legacy-template/publish.js' {
  declare module.exports: $Exports<'@webdoc/legacy-template/publish'>;
}
declare module '@webdoc/legacy-template/src/AttributesBuilder.js' {
  declare module.exports: $Exports<'@webdoc/legacy-template/src/AttributesBuilder'>;
}
declare module '@webdoc/legacy-template/src/SignatureBuilder.js' {
  declare module.exports: $Exports<'@webdoc/legacy-template/src/SignatureBuilder'>;
}
declare module '@webdoc/legacy-template/static/scripts/linenumber.js' {
  declare module.exports: $Exports<'@webdoc/legacy-template/static/scripts/linenumber'>;
}
