// flow-typed signature: 7dd181b538c4dc3ee8ca3336ab7856ad
// flow-typed version: <<STUB>>/missionlog_v1.6.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'missionlog'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'missionlog' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'missionlog/index' {
  declare module.exports: $Exports<'missionlog'>;
}
declare module 'missionlog/index.js' {
  declare module.exports: $Exports<'missionlog'>;
}
