// flow-typed signature: b71422e8a5dccfc9279b581f6a5dc4a0
// flow-typed version: <<STUB>>/@sentry/node_v7.2.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/node' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/node/cjs/client' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/eventbuilder' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/handlers' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/console' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/contextlines' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/http' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/modules' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/onuncaughtexception' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/onunhandledrejection' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/utils/errorhandling' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/integrations/utils/http' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/module' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/requestDataDeprecated' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/sdk' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/stack-parser' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/transports/http' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/transports' {
  declare module.exports: any;
}

declare module '@sentry/node/cjs/utils' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/client' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/eventbuilder' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/handlers' {
  declare module.exports: any;
}

declare module '@sentry/node/esm' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/console' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/contextlines' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/http' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/linkederrors' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/modules' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/onuncaughtexception' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/onunhandledrejection' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/utils/errorhandling' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/integrations/utils/http' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/module' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/requestDataDeprecated' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/sdk' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/stack-parser' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/transports/http' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/transports' {
  declare module.exports: any;
}

declare module '@sentry/node/esm/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/node/cjs/client.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/client'>;
}
declare module '@sentry/node/cjs/eventbuilder.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/eventbuilder'>;
}
declare module '@sentry/node/cjs/handlers.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/handlers'>;
}
declare module '@sentry/node/cjs/index' {
  declare module.exports: $Exports<'@sentry/node/cjs'>;
}
declare module '@sentry/node/cjs/index.js' {
  declare module.exports: $Exports<'@sentry/node/cjs'>;
}
declare module '@sentry/node/cjs/integrations/console.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/console'>;
}
declare module '@sentry/node/cjs/integrations/contextlines.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/contextlines'>;
}
declare module '@sentry/node/cjs/integrations/http.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/http'>;
}
declare module '@sentry/node/cjs/integrations/index' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations'>;
}
declare module '@sentry/node/cjs/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations'>;
}
declare module '@sentry/node/cjs/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/linkederrors'>;
}
declare module '@sentry/node/cjs/integrations/modules.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/modules'>;
}
declare module '@sentry/node/cjs/integrations/onuncaughtexception.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/onuncaughtexception'>;
}
declare module '@sentry/node/cjs/integrations/onunhandledrejection.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/onunhandledrejection'>;
}
declare module '@sentry/node/cjs/integrations/utils/errorhandling.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/utils/errorhandling'>;
}
declare module '@sentry/node/cjs/integrations/utils/http.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/integrations/utils/http'>;
}
declare module '@sentry/node/cjs/module.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/module'>;
}
declare module '@sentry/node/cjs/requestDataDeprecated.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/requestDataDeprecated'>;
}
declare module '@sentry/node/cjs/sdk.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/sdk'>;
}
declare module '@sentry/node/cjs/stack-parser.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/stack-parser'>;
}
declare module '@sentry/node/cjs/transports/http.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/transports/http'>;
}
declare module '@sentry/node/cjs/transports/index' {
  declare module.exports: $Exports<'@sentry/node/cjs/transports'>;
}
declare module '@sentry/node/cjs/transports/index.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/transports'>;
}
declare module '@sentry/node/cjs/utils.js' {
  declare module.exports: $Exports<'@sentry/node/cjs/utils'>;
}
declare module '@sentry/node/esm/client.js' {
  declare module.exports: $Exports<'@sentry/node/esm/client'>;
}
declare module '@sentry/node/esm/eventbuilder.js' {
  declare module.exports: $Exports<'@sentry/node/esm/eventbuilder'>;
}
declare module '@sentry/node/esm/handlers.js' {
  declare module.exports: $Exports<'@sentry/node/esm/handlers'>;
}
declare module '@sentry/node/esm/index' {
  declare module.exports: $Exports<'@sentry/node/esm'>;
}
declare module '@sentry/node/esm/index.js' {
  declare module.exports: $Exports<'@sentry/node/esm'>;
}
declare module '@sentry/node/esm/integrations/console.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/console'>;
}
declare module '@sentry/node/esm/integrations/contextlines.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/contextlines'>;
}
declare module '@sentry/node/esm/integrations/http.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/http'>;
}
declare module '@sentry/node/esm/integrations/index' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations'>;
}
declare module '@sentry/node/esm/integrations/index.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations'>;
}
declare module '@sentry/node/esm/integrations/linkederrors.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/linkederrors'>;
}
declare module '@sentry/node/esm/integrations/modules.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/modules'>;
}
declare module '@sentry/node/esm/integrations/onuncaughtexception.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/onuncaughtexception'>;
}
declare module '@sentry/node/esm/integrations/onunhandledrejection.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/onunhandledrejection'>;
}
declare module '@sentry/node/esm/integrations/utils/errorhandling.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/utils/errorhandling'>;
}
declare module '@sentry/node/esm/integrations/utils/http.js' {
  declare module.exports: $Exports<'@sentry/node/esm/integrations/utils/http'>;
}
declare module '@sentry/node/esm/module.js' {
  declare module.exports: $Exports<'@sentry/node/esm/module'>;
}
declare module '@sentry/node/esm/requestDataDeprecated.js' {
  declare module.exports: $Exports<'@sentry/node/esm/requestDataDeprecated'>;
}
declare module '@sentry/node/esm/sdk.js' {
  declare module.exports: $Exports<'@sentry/node/esm/sdk'>;
}
declare module '@sentry/node/esm/stack-parser.js' {
  declare module.exports: $Exports<'@sentry/node/esm/stack-parser'>;
}
declare module '@sentry/node/esm/transports/http.js' {
  declare module.exports: $Exports<'@sentry/node/esm/transports/http'>;
}
declare module '@sentry/node/esm/transports/index' {
  declare module.exports: $Exports<'@sentry/node/esm/transports'>;
}
declare module '@sentry/node/esm/transports/index.js' {
  declare module.exports: $Exports<'@sentry/node/esm/transports'>;
}
declare module '@sentry/node/esm/utils.js' {
  declare module.exports: $Exports<'@sentry/node/esm/utils'>;
}
