// flow-typed signature: 4823f658541969a025a76c401c20ff57
// flow-typed version: <<STUB>>/gunzip-maybe_v1.4.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gunzip-maybe'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gunzip-maybe' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gunzip-maybe/bin' {
  declare module.exports: any;
}

declare module 'gunzip-maybe/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gunzip-maybe/bin.js' {
  declare module.exports: $Exports<'gunzip-maybe/bin'>;
}
declare module 'gunzip-maybe/index' {
  declare module.exports: $Exports<'gunzip-maybe'>;
}
declare module 'gunzip-maybe/index.js' {
  declare module.exports: $Exports<'gunzip-maybe'>;
}
declare module 'gunzip-maybe/test.js' {
  declare module.exports: $Exports<'gunzip-maybe/test'>;
}
