// flow-typed signature: 49d3b59d1e10f8fffc80e69acf8fd29d
// flow-typed version: <<STUB>>/object.fromentries_v^2.0.2/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'object.fromentries'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'object.fromentries' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'object.fromentries/auto' {
  declare module.exports: any;
}

declare module 'object.fromentries/implementation' {
  declare module.exports: any;
}

declare module 'object.fromentries/polyfill' {
  declare module.exports: any;
}

declare module 'object.fromentries/shim' {
  declare module.exports: any;
}

declare module 'object.fromentries/test/implementation' {
  declare module.exports: any;
}

declare module 'object.fromentries/test' {
  declare module.exports: any;
}

declare module 'object.fromentries/test/shimmed' {
  declare module.exports: any;
}

declare module 'object.fromentries/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'object.fromentries/auto.js' {
  declare module.exports: $Exports<'object.fromentries/auto'>;
}
declare module 'object.fromentries/implementation.js' {
  declare module.exports: $Exports<'object.fromentries/implementation'>;
}
declare module 'object.fromentries/index' {
  declare module.exports: $Exports<'object.fromentries'>;
}
declare module 'object.fromentries/index.js' {
  declare module.exports: $Exports<'object.fromentries'>;
}
declare module 'object.fromentries/polyfill.js' {
  declare module.exports: $Exports<'object.fromentries/polyfill'>;
}
declare module 'object.fromentries/shim.js' {
  declare module.exports: $Exports<'object.fromentries/shim'>;
}
declare module 'object.fromentries/test/implementation.js' {
  declare module.exports: $Exports<'object.fromentries/test/implementation'>;
}
declare module 'object.fromentries/test/index' {
  declare module.exports: $Exports<'object.fromentries/test'>;
}
declare module 'object.fromentries/test/index.js' {
  declare module.exports: $Exports<'object.fromentries/test'>;
}
declare module 'object.fromentries/test/shimmed.js' {
  declare module.exports: $Exports<'object.fromentries/test/shimmed'>;
}
declare module 'object.fromentries/test/tests.js' {
  declare module.exports: $Exports<'object.fromentries/test/tests'>;
}
