// flow-typed signature: 049a9c01cdf78733d0c53fdf43c83278
// flow-typed version: <<STUB>>/pkg-up_v~3.1.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pkg-up'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pkg-up' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pkg-up/index' {
  declare module.exports: $Exports<'pkg-up'>;
}
declare module 'pkg-up/index.js' {
  declare module.exports: $Exports<'pkg-up'>;
}
