// flow-typed signature: 6eafa8c8ac99ad56b932e347d146f1a9
// flow-typed version: <<STUB>>/@webdoc/language-parser_v^1.6.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/language-parser'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/language-parser' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webdoc/language-parser/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webdoc/language-parser/lib/index' {
  declare module.exports: $Exports<'@webdoc/language-parser/lib'>;
}
declare module '@webdoc/language-parser/lib/index.js' {
  declare module.exports: $Exports<'@webdoc/language-parser/lib'>;
}
