// flow-typed signature: c0fb90a45104969960fb35671d41f9d1
// flow-typed version: <<STUB>>/@webdoc/configure-rollup_v^1.6.1/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/configure-rollup'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/configure-rollup' {
  declare module.exports: any;
}
