// flow-typed signature: d4ef40d42e34b985f6004e86be59a78d
// flow-typed version: <<STUB>>/@webdoc/stub_v^1.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/stub'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/stub' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webdoc/stub/cli' {
  declare module.exports: any;
}

declare module '@webdoc/stub/lib' {
  declare module.exports: any;
}

declare module '@webdoc/stub/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webdoc/stub/cli.js' {
  declare module.exports: $Exports<'@webdoc/stub/cli'>;
}
declare module '@webdoc/stub/lib/index' {
  declare module.exports: $Exports<'@webdoc/stub/lib'>;
}
declare module '@webdoc/stub/lib/index.js' {
  declare module.exports: $Exports<'@webdoc/stub/lib'>;
}
declare module '@webdoc/stub/src/index' {
  declare module.exports: $Exports<'@webdoc/stub/src'>;
}
declare module '@webdoc/stub/src/index.js' {
  declare module.exports: $Exports<'@webdoc/stub/src'>;
}
