// flow-typed signature: c38fd0cce9c79823c5e1563a3c32fae7
// flow-typed version: <<STUB>>/@webdoc/language-library_v^1.6.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/language-library'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/language-library' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webdoc/language-library/index.flow' {
  declare module.exports: any;
}

declare module '@webdoc/language-library/lib' {
  declare module.exports: any;
}

declare module '@webdoc/language-library/src' {
  declare module.exports: any;
}

declare module '@webdoc/language-library/src/Logger' {
  declare module.exports: any;
}

declare module '@webdoc/language-library/src/Symbol' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webdoc/language-library/index.flow.js' {
  declare module.exports: $Exports<'@webdoc/language-library/index.flow'>;
}
declare module '@webdoc/language-library/lib/index' {
  declare module.exports: $Exports<'@webdoc/language-library/lib'>;
}
declare module '@webdoc/language-library/lib/index.js' {
  declare module.exports: $Exports<'@webdoc/language-library/lib'>;
}
declare module '@webdoc/language-library/src/index' {
  declare module.exports: $Exports<'@webdoc/language-library/src'>;
}
declare module '@webdoc/language-library/src/index.js' {
  declare module.exports: $Exports<'@webdoc/language-library/src'>;
}
declare module '@webdoc/language-library/src/Logger.js' {
  declare module.exports: $Exports<'@webdoc/language-library/src/Logger'>;
}
declare module '@webdoc/language-library/src/Symbol.js' {
  declare module.exports: $Exports<'@webdoc/language-library/src/Symbol'>;
}
