// flow-typed signature: bd9c4fb37b59ba1731e6540e340818af
// flow-typed version: <<STUB>>/@webdoc/babel-preset_v^1.0.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/babel-preset'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/babel-preset' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@webdoc/babel-preset/index' {
  declare module.exports: $Exports<'@webdoc/babel-preset'>;
}
declare module '@webdoc/babel-preset/index.js' {
  declare module.exports: $Exports<'@webdoc/babel-preset'>;
}
