// flow-typed signature: 8dac2b2ebb5f923fe50d014a0eaf6c7a
// flow-typed version: <<STUB>>/@webdoc/plugin-markdown_v^1.6.6/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@webdoc/plugin-markdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@webdoc/plugin-markdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@webdoc/plugin-markdown/Gulpfile.babel' {
  declare module.exports: any;
}

declare module '@webdoc/plugin-markdown/lib' {
  declare module.exports: any;
}

declare module '@webdoc/plugin-markdown/src' {
  declare module.exports: any;
}

// Filename aliases
declare module '@webdoc/plugin-markdown/Gulpfile.babel.js' {
  declare module.exports: $Exports<'@webdoc/plugin-markdown/Gulpfile.babel'>;
}
declare module '@webdoc/plugin-markdown/lib/index' {
  declare module.exports: $Exports<'@webdoc/plugin-markdown/lib'>;
}
declare module '@webdoc/plugin-markdown/lib/index.js' {
  declare module.exports: $Exports<'@webdoc/plugin-markdown/lib'>;
}
declare module '@webdoc/plugin-markdown/src/index' {
  declare module.exports: $Exports<'@webdoc/plugin-markdown/src'>;
}
declare module '@webdoc/plugin-markdown/src/index.js' {
  declare module.exports: $Exports<'@webdoc/plugin-markdown/src'>;
}
