// flow-typed signature: fcf8a05deac56af05746026b4555c597
// flow-typed version: <<STUB>>/@sentry/integrations_v7.2.0/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@sentry/integrations'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@sentry/integrations' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@sentry/integrations/cjs/captureconsole' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/debug' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/dedupe' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/extraerrordata' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/offline' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/reportingobserver' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/rewriteframes' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/sessiontiming' {
  declare module.exports: any;
}

declare module '@sentry/integrations/cjs/transaction' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/captureconsole' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/debug' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/dedupe' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/extraerrordata' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/offline' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/reportingobserver' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/rewriteframes' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/sessiontiming' {
  declare module.exports: any;
}

declare module '@sentry/integrations/esm/transaction' {
  declare module.exports: any;
}

// Filename aliases
declare module '@sentry/integrations/cjs/captureconsole.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/captureconsole'>;
}
declare module '@sentry/integrations/cjs/debug.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/debug'>;
}
declare module '@sentry/integrations/cjs/dedupe.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/dedupe'>;
}
declare module '@sentry/integrations/cjs/extraerrordata.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/extraerrordata'>;
}
declare module '@sentry/integrations/cjs/index' {
  declare module.exports: $Exports<'@sentry/integrations/cjs'>;
}
declare module '@sentry/integrations/cjs/index.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs'>;
}
declare module '@sentry/integrations/cjs/offline.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/offline'>;
}
declare module '@sentry/integrations/cjs/reportingobserver.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/reportingobserver'>;
}
declare module '@sentry/integrations/cjs/rewriteframes.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/rewriteframes'>;
}
declare module '@sentry/integrations/cjs/sessiontiming.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/sessiontiming'>;
}
declare module '@sentry/integrations/cjs/transaction.js' {
  declare module.exports: $Exports<'@sentry/integrations/cjs/transaction'>;
}
declare module '@sentry/integrations/esm/captureconsole.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/captureconsole'>;
}
declare module '@sentry/integrations/esm/debug.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/debug'>;
}
declare module '@sentry/integrations/esm/dedupe.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/dedupe'>;
}
declare module '@sentry/integrations/esm/extraerrordata.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/extraerrordata'>;
}
declare module '@sentry/integrations/esm/index' {
  declare module.exports: $Exports<'@sentry/integrations/esm'>;
}
declare module '@sentry/integrations/esm/index.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm'>;
}
declare module '@sentry/integrations/esm/offline.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/offline'>;
}
declare module '@sentry/integrations/esm/reportingobserver.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/reportingobserver'>;
}
declare module '@sentry/integrations/esm/rewriteframes.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/rewriteframes'>;
}
declare module '@sentry/integrations/esm/sessiontiming.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/sessiontiming'>;
}
declare module '@sentry/integrations/esm/transaction.js' {
  declare module.exports: $Exports<'@sentry/integrations/esm/transaction'>;
}
