// flow-typed signature: 96bebfcc1da53b0d12c6ad41006e4e56
// flow-typed version: <<STUB>>/array.prototype.flatmap_v~1.2.3/flow_v0.130.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'array.prototype.flatmap'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'array.prototype.flatmap' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'array.prototype.flatmap/auto' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/implementation' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/polyfill' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/shim' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/test/implementation' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/test' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/test/shimmed' {
  declare module.exports: any;
}

declare module 'array.prototype.flatmap/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'array.prototype.flatmap/auto.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/auto'>;
}
declare module 'array.prototype.flatmap/implementation.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/implementation'>;
}
declare module 'array.prototype.flatmap/index' {
  declare module.exports: $Exports<'array.prototype.flatmap'>;
}
declare module 'array.prototype.flatmap/index.js' {
  declare module.exports: $Exports<'array.prototype.flatmap'>;
}
declare module 'array.prototype.flatmap/polyfill.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/polyfill'>;
}
declare module 'array.prototype.flatmap/shim.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/shim'>;
}
declare module 'array.prototype.flatmap/test/implementation.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/test/implementation'>;
}
declare module 'array.prototype.flatmap/test/index' {
  declare module.exports: $Exports<'array.prototype.flatmap/test'>;
}
declare module 'array.prototype.flatmap/test/index.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/test'>;
}
declare module 'array.prototype.flatmap/test/shimmed.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/test/shimmed'>;
}
declare module 'array.prototype.flatmap/test/tests.js' {
  declare module.exports: $Exports<'array.prototype.flatmap/test/tests'>;
}
